# -*- coding: utf-8 -*-
"""Projeto de cadastramento de usúario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3KZ_s3Bhr7nhdP3spxPl2eOIyK_N_My
"""

usuarios = []
print("///// BEM VINDO AO CADASTRAMENTO DO USUARIO DO IFOOD /////////// ")
print("Para iniciarmos segue abaixo as opções para cadastramento de usuário: ")
while True:
  print("1 Cadastrar usuário")
  print("2- Ver cadastros")
  print("3- Excluir cadastro")
  print("4- Sair")

  Opcao = int(input("Por favor selecione a opção desejada: "))

  if Opcao == 1:
      print("Opção selecionada foi cadastrar usuário")

      nome = input("Digite seu nome: ")
      idade = int(input("Digite sua idade: "))
      email = input("Digite seu email: ")

      usuario = {
          "nome": nome,
          "idade": idade,
          "email": email
      }
      usuarios.append(usuario)
      print("Usuário cadastrado com sucesso!")

  elif Opcao == 2:
      print("Opção selecionada foi ver cadastro")

      if len(usuarios) == 0:
        print("Nenhum usuário cadastrado")
      else:
        for usuario in usuarios:
          print(usuario)
  elif Opcao == 3:
        print("Opção selecionada foi excluir cadastro")
        nome_remover = input("Por favor, digite o nome do usuario que deseja excluir: ")
        encontrado = False
        for usuario in usuarios:
          if usuario["nome"] == nome_remover:
            usuarios.remove(usuario)
            print("Usuário removido com sucesso!")
            encontrado = True
            break
        if not encontrado:
            print("Usuário não encontrado")
  elif Opcao == 4:
      print("Opção selecionada foi sair, até mais!")
      break

from google.colab import drive
drive.mount('/content/drive')